Component/chart
drippy-iot/dashboard pull request #15
Opened 2023-05-31 11:41 UTC by mmfallacy

This PR introduces the Chart component which serves as the primary data visualization for the flow rate.

2023-06-01 09:31 UTC, BastiDood requested changes

2023-06-01 09:31 UTC, BastiDood commented on src/components/Chart/Display.svelte
> +    import colors from 'tailwindcss/colors';
Just reordering some imports here. I basically alphabetized by the name of the third-party package.
```suggestion
    import type { ChartConfiguration } from 'chart.js';
    import Chart from 'chart.js/auto';
    import ChartStreaming from 'chartjs-plugin-streaming';
    import ChartZoom from 'chartjs-plugin-zoom';
    import { onMount } from 'svelte';
    import colors from 'tailwindcss/colors';

    import 'chartjs-adapter-date-fns';

    import { flow } from './mock.ts';
```

2023-06-01 09:31 UTC, BastiDood commented on src/routes/Dashboard/Page.svelte
There is apparently one usage of `Spacer` that is declared but never used. The indentation is also inconsistent in the imports.

2023-06-01 09:31 UTC, BastiDood commented on src/components/Chart/Display.svelte
> +        $flow = [];
I believe we may use mutation here to make it more efficient.
```suggestion
        const points = $flow
            .splice(0)
            .map(({ ts, flow }) => ({
                x: ts.getTime(),
                y: flow,
            }));
        $flow = $flow; // notify mutation
        chart?.data.datasets[0]?.data.push(...points);
```

2023-06-02 15:09 UTC, mmfallacy commented on src/routes/Dashboard/Page.svelte
Removed in [cd3601b](https://github.com/drippy-iot/dashboard/pull/15/commits/cd3601b671016fc6fb33c8c2b853e4183bfb4606)

2023-06-02 15:26 UTC, BastiDood approved these changes

2023-06-02 15:26 UTC, merged